# Generated by Django 2.2 on 2019-11-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('banner_title', models.CharField(blank=True, max_length=50, null=True)),
                ('banner_path', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
